"""Assemble charts and summary into a self-contained HTML report."""

import webbrowser
from pathlib import Path

import pandas as pd
import plotly.io as pio

from engine.backtester import BacktestResult
from reporting.charts import (
    create_equity_curve_chart,
    create_monthly_heatmap,
    create_trade_scatter,
    create_r_distribution,
    create_mae_mfe_scatter,
)
from reporting.summary import print_summary


def generate_report(
    result: BacktestResult,
    output_dir: str | Path = "output",
    open_browser: bool = False,
) -> Path:
    """Generate a self-contained HTML backtest report.

    Parameters
    ----------
    result : BacktestResult
        Complete output from a backtest run.
    output_dir : str | Path
        Directory to write the report file into.
    open_browser : bool
        If True, open the report in the default browser after writing.

    Returns
    -------
    Path
        Absolute path to the generated ``report.html`` file.
    """
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)

    # 1. Print console summary and capture the text
    summary_text = print_summary(result)

    # 2. Generate all 5 charts
    chart_figures = [
        ("Equity Curve", create_equity_curve_chart(result)),
        ("Monthly Returns", create_monthly_heatmap(result)),
        ("Trade Results", create_trade_scatter(result)),
        ("R-Multiple Distribution", create_r_distribution(result)),
        ("MAE vs MFE", create_mae_mfe_scatter(result)),
    ]

    # 3. Convert each chart to an HTML div (without full page / plotly.js)
    charts: list[tuple[str, str]] = []
    for title, fig in chart_figures:
        div_html = pio.to_html(fig, full_html=False, include_plotlyjs=False)
        charts.append((title, div_html))

    # 4. Build trade table HTML
    trade_table_html = _trade_log_to_html(result.trade_log)

    # 5. Assemble full HTML document
    html = _build_html(summary_text, charts, trade_table_html, result.metrics)

    # 6. Write to disk
    report_file = output_path / "report.html"
    report_file.write_text(html, encoding="utf-8")

    # 7. Optionally open in browser
    if open_browser:
        webbrowser.open(report_file.resolve().as_uri())

    return report_file


def _build_html(
    summary_text: str,
    charts: list[tuple[str, str]],
    trade_table_html: str,
    metrics: object,
) -> str:
    """Build a self-contained HTML document from report components.

    Parameters
    ----------
    summary_text : str
        Pre-formatted console summary text.
    charts : list[tuple[str, str]]
        List of (title, plotly_div_html) pairs.
    trade_table_html : str
        HTML string for the trade log table.
    metrics : MetricsResult
        Metrics object (reserved for future use in the template).

    Returns
    -------
    str
        Complete HTML document as a string.
    """
    # Build chart sections
    chart_sections: list[str] = []
    for title, div_html in charts:
        chart_sections.append(
            f'        <h2>{title}</h2>\n'
            f'        <div class="chart-container">{div_html}</div>'
        )
    charts_html = "\n\n".join(chart_sections)

    return f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>IRS Backtest Report</title>
    <script src="https://cdn.plot.ly/plotly-2.35.2.min.js"></script>
    <style>
        body {{ background: #1a1a2e; color: #e0e0e0; font-family: 'Segoe UI', sans-serif; margin: 0; padding: 20px; }}
        .container {{ max-width: 1200px; margin: 0 auto; }}
        h1 {{ text-align: center; color: #26a69a; }}
        h2 {{ color: #26a69a; border-bottom: 1px solid #333; padding-bottom: 8px; }}
        pre {{ background: #16213e; padding: 16px; border-radius: 8px; overflow-x: auto; font-size: 13px; line-height: 1.6; }}
        .chart-container {{ margin: 20px 0; }}
        table {{ width: 100%; border-collapse: collapse; font-size: 13px; }}
        th {{ background: #16213e; color: #26a69a; padding: 8px; text-align: left; }}
        td {{ padding: 6px 8px; border-bottom: 1px solid #333; }}
        tr:hover {{ background: #16213e; }}
        .win {{ color: #26a69a; }}
        .loss {{ color: #ef5350; }}
        .be {{ color: #888888; }}
        .footer {{ text-align: center; color: #666; margin-top: 40px; font-size: 12px; }}
    </style>
</head>
<body>
    <div class="container">
        <h1>IRS Backtest Report</h1>

        <h2>Summary</h2>
        <pre>{summary_text}</pre>

{charts_html}

        <h2>Trade Log</h2>
        {trade_table_html}

        <div class="footer">
            Generated by IRS Backtesting System
        </div>
    </div>
</body>
</html>"""


def _trade_log_to_html(trade_df: pd.DataFrame) -> str:
    """Convert a trade log DataFrame to an HTML table.

    Parameters
    ----------
    trade_df : pd.DataFrame
        Trade log with columns including trade_id, direction, entry_time,
        entry_price, exit_time, exit_price, r_multiple, realized_pnl,
        duration_bars, outcome, sync_mode.

    Returns
    -------
    str
        HTML table string, or a ``<p>`` tag if the DataFrame is empty.
    """
    if trade_df is None or len(trade_df) == 0:
        return "<p>No trades executed.</p>"

    max_rows = 200
    total_trades = len(trade_df)
    display_df = trade_df.head(max_rows)

    rows: list[str] = []
    for idx, trade in display_df.iterrows():
        # Direction formatting
        direction_raw = trade.get("direction", "")
        if direction_raw == 1 or direction_raw == "+1":
            direction = "LONG"
        elif direction_raw == -1 or direction_raw == "-1":
            direction = "SHORT"
        else:
            direction = str(direction_raw)

        # Time formatting
        entry_time = trade.get("entry_time", None)
        if pd.notna(entry_time):
            try:
                entry_time_str = pd.Timestamp(entry_time).strftime("%Y-%m-%d %H:%M")
            except Exception:
                entry_time_str = str(entry_time)
        else:
            entry_time_str = "N/A"

        exit_time = trade.get("exit_time", None)
        if pd.notna(exit_time):
            try:
                exit_time_str = pd.Timestamp(exit_time).strftime("%Y-%m-%d %H:%M")
            except Exception:
                exit_time_str = str(exit_time)
        else:
            exit_time_str = "N/A"

        # Numeric formatting
        entry_price = trade.get("entry_price", 0.0)
        exit_price = trade.get("exit_price", 0.0)
        r_multiple = trade.get("r_multiple", 0.0)
        realized_pnl = trade.get("realized_pnl", 0.0)
        duration_bars = trade.get("duration_bars", 0)
        outcome = trade.get("outcome", "")
        sync_mode = trade.get("sync_mode", "")

        # Row CSS class based on outcome
        outcome_upper = str(outcome).upper()
        if outcome_upper == "WIN":
            row_class = "win"
        elif outcome_upper == "LOSS":
            row_class = "loss"
        elif outcome_upper == "BREAKEVEN":
            row_class = "be"
        else:
            row_class = ""

        trade_num = idx + 1 if isinstance(idx, int) else trade.get("trade_id", idx)

        row_html = (
            f'<tr class="{row_class}">'
            f"<td>{trade_num}</td>"
            f"<td>{direction}</td>"
            f"<td>{entry_time_str}</td>"
            f"<td>{entry_price:.2f}</td>"
            f"<td>{exit_time_str}</td>"
            f"<td>{exit_price:.2f}</td>"
            f"<td>{r_multiple:.2f}R</td>"
            f"<td>${realized_pnl:,.2f}</td>"
            f"<td>{int(duration_bars)} bars</td>"
            f"<td>{outcome}</td>"
            f"<td>{sync_mode}</td>"
            f"</tr>"
        )
        rows.append(row_html)

    rows_html = "\n".join(rows)

    truncation_note = ""
    if total_trades > max_rows:
        truncation_note = (
            f'<p style="color: #888; font-size: 12px;">'
            f"Showing {max_rows} of {total_trades} trades</p>"
        )

    return f"""<table>
<thead>
<tr>
    <th>#</th>
    <th>Dir</th>
    <th>Entry Time</th>
    <th>Entry Price</th>
    <th>Exit Time</th>
    <th>Exit Price</th>
    <th>R-Multiple</th>
    <th>PnL</th>
    <th>Duration</th>
    <th>Outcome</th>
    <th>Sync</th>
</tr>
</thead>
<tbody>
{rows_html}
</tbody>
</table>
{truncation_note}"""
